### ISSUE TITLE
TabbedPane Components Location

### ISSUE THREAD

**Issue by Siedg** [BloodShura/MPSBot#1]
TabbedPane doesn't display the correct location of each component.

**Comment by BloodShura** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by thiagohoh** [comment]
O cara veio escrever em latim aqui vai tomar no cu ahahhahaaha
@Siedg

**Comment by BloodShura** [comment]
eu comemto onde eu kiser ermão tlgd se subir aki no morro pd xamar os alemao tlgd que aki a firma eh forte pode pa!!1!!onze!

**Comment by Siedg** [comment]
Wtf virou bagunça?

**Comment by Siedg** [comment]
Thiago já resolveu.

**Comment by BloodShura** [comment]
Glória mainha, esse cabra da peste resolveste a marlota, vishe?

**Comment by BloodShura** [comment]
Ó eu com boné

**Comment by BloodShura** [comment]
Ó eu sem boné

**Comment by BloodShura** [comment]
Ó eu com boné

**Comment by BloodShura** [comment]
Ó eu sem boné
